// Generated by https://quicktype.io

export interface PlaceResponse {
    type: string;
    query: string[];
    features: Feature[];
    attribution: string;
}

export interface Feature {
    id: string;
    type: string;
    place_type: string[];
    relevance: number;
    properties: Properties;
    text_es: string;
    language_es?: string;
    place_name_es: string;
    text: string;
    language?: string;
    place_name: string;
    matching_text?: string;
    matching_place_name?: string;
    center: number[];
    geometry: Geometry;
    context: Context[];
}

export interface Context {
    id: string;
    mapbox_id: string;
    text_es: string;
    text: string;
    wikidata?: string;
    language_es?: Language;
    language?: Language;
    short_code?: Language;
}

export enum Language {
    Es = "es",
    EsB = "ES-B",
    EsT = "ES-T",
}

export interface Geometry {
    coordinates: number[];
    type: string;
}

export interface Properties {
    foursquare: string;
    landmark: boolean;
    address: string;
    category: string;
}
